### ISSUE TITLE
use out of the box primary key "id" instead of "uuid" 

### ISSUE THREAD

**Issue by dmontoya-ai** [verbanent/eloquent-binary-uuid#8]
Why do you use a different field for primary key on all tables?

How can I change this project to use the out of the box primary key name "id" instead of yours "uuid" one. I don't want to change all my existing code to use uuid instead 
![uuid](https://user-images.githubusercontent.com/79985915/141482765-3b464700-191e-470e-9ecf-58c90927d967.png)
of id.

**Comment by radek-ziemniewicz** [comment]
Thanks, @dmontoya-ai, that's a brilliant idea! It's been fixed in v1.7.0:
https://github.com/verbanent/eloquent-binary-uuid/releases/tag/v1.7.0

**Comment by egarcia-add** [comment]
Hi,

We was using your library but can't update with this change. Our uuid column name is uuid but is not the primary_key for the table (id instead) so now the library is always searching for id column which is a number.

Could you add a way to describe a custom column for uuid without being the result of **getKeyName** method?

I'm thinking in something like describe in the model a column:

public $uuidColumn = 'uuid'; 

Thanks for your work!

**Comment by radek-ziemniewicz** [comment]
@egarcia-add, that's a good point. I used your suggestion and fixed it in v1.7.2:
https://github.com/verbanent/eloquent-binary-uuid/releases/tag/v1.7.2
Thanks!
